### PR TITLE
Support reading AWS credentials from ~/.aws/credentials.

### PR DESCRIPTION
**Pull request by lrowe**
See: http://boto.readthedocs.org/en/latest/boto_config_tut.html#credentials

### CODE REVIEW

**Comment by fdr** [comment]
I'm not keen on adding Yet Another Way to get credentials into the system. There are the ones with somewhat unique properties like instance profiles, so that seems reasonable, but what about this is sufficiently better than environment variables?

**Comment by lrowe** [comment]
Reading credentials from ~/.aws/credentials makes it easy to use the official aws-cli client to verify that the permissions are correctly granted. It also simplifies deployments by avoiding the need to install envdir/daemontools and a small file per environment variable as there is just one file to transfer.

I don't really need multi-profile support though, if wal-e would fallback to using the default credentials in the file by not raising an error in `s3_explicit_creds` (https://github.com/wal-e/wal-e/blob/master/wal_e/cmd.py#L393) that'd work just as well for me.

**Comment by slotrans** [comment]
Honestly wal-e should just throw away its custom ways of doing AWS authentication and let boto handle it automatically.  That would give wal-e support for pulling credentials from ~/.aws, environment variables, and IAM instance roles with zero configuration.

**Comment by fdr** [comment]
The reason I've had to do so much random crap with the authentication to begin with is because Boto would not do a sufficient job at certain things like learning the right calling convention on an endpoint.  This caused a number of bug reports, and ultimately had to be dealt with for multi-region.  [These problems may or may not be fixed](https://github.com/boto/boto/issues/443), but many people run with older Botos, e.g. those managed by an operating system.

Secondarily, although this is one of my perennial projects, I am intending to have WAL-E support multiple prefixes, maybe sometime in the next year, and that means multiple prefixes and credentials associated with each.

Thirdly, I find the idea that the precedence and source of authentication configuration for WAL-E can only be divined by some programming library manual unpalatable.  This can lead to serious problems because of deficiencies in S3, such as uploading segments with the wrong ownership: there is no way to fix this outside downloading and re-uploading those keys.

**Comment by fdr** [comment]
Maybe I'll revisit this with a boto3 port.

**Pull request closed without merging**
