### PR TITLE
Add --permanent option to really delete objects from a versioned s3 bucket

### PR DESCRIPTION
**Pull request by emenendez**
Normally, when running wal-e delete on a versioned s3 bucket, s3 simply adds a "delete marker" over top of each deleted object. This is the intent of bucket versioning, but it is not helpful if backups need to be removed to save storage costs. This PR adds a --permanent flag to the delete command which, when invoked and used with a versioned s3 bucket, will permanently delete the most recent version of each s3 object instead of inserting a delete marker.

### CODE REVIEW

**Comment by fdr** [comment]
Is there any way to make this not-an-option? For example, does anyone not want permanence?

**Comment by emenendez** [comment]
I'd be happy to refactor this PR so objects are always permanently deleted.
However, one caveat is although this code will work just fine on a non-versioned bucket, it does require the s3:ListBucketVersions permission; any users working with non-versioned buckets who don't already have the s3:ListBucketVersions in their policy may be surprised to find wal-e stops working. If that's not a roadblock, then it's simple to make this always-on behavior.

**Comment by will-ob** [comment]
+1 +1 +1
:+1:

**Comment by gregorysabatino** [comment]
:+1: :+1:

**Comment by fdr** [comment]
Upon consideration, I think `permanent` should be the only option. The whole point of wal-e delete is to control costs and save space, so I think being overly polite with regard to deletion while versioning is overwrought. Can you streamline the patch to remove the option and make WAL-E handle both versioned and unversioned buckets.

**Comment by fdr** [comment]
Can anyone modify this patch to make `permanent` the default behavior and fall back gracefully if one uses an unversioned bucket? If so I'll commit it.

**Comment by emenendez** [comment]
Verified this works with a versioned bucket; still working on getting a non-versioned bucket set up to test.

**Comment by jtyoung** [comment]
I know this issue is pretty stale at this point, but I've just experienced this exact issue. My S3 bucket storing my backups and WAL archives is only a few terabytes on disk, but the bucket size is hundreds of terabytes (and costing some serious $$) because of the versioning markers. 

Luckily, finding this issue tipped me off as to what might be happening, but it would still be nice to have this feature (or a flag to use it) merged into master.

**Comment by fdr** [comment]
I'm applying the newly introduced `needs-work` label to this. That is, there is no problem with the feature in principal, but there's a lack of interest, testing, or changes to complete it. I also apply this label so I can find such closed pull requests easily for future study.

**Pull request closed without merging**
