### PR TITLE
Add Google Cloud Storage support

### PR DESCRIPTION
**Pull request by deverant**
@fdr, let me know if I should squash this somehow. For now I wanted to keep the work done by different parties separate and have each commit fix only one thing.

This fixes #211.

### CODE REVIEW

**Comment by fdr** [comment]
Thanks, that's helpful, I'll probably squash in the end but it's useful for review for me to see your deltas.

I will try to make a block of time over the next couple of weeks to apply this. It'll probably indicate a new release, probably WAL-E v1.0.

**Comment by fdr** [comment]
Okay, one question: do you use this/can you test this with GCE instance metadata, defined creds, or both? That's one errata in the patch that doesn't have clear resolution. Otherwise, I suppose I can remove mention of it for another interested party.

**Comment by fdr** [comment]
Another question: how would you feel about batching this with an upgrade to Python3? 

I was waiting for Gevent to support Python3, and it is the last of my dependencies to do so: the time is finally here. But seeing as you pushed this over the finish line, I wanted to make a release that would suit your needs, all else being close to equal.

**Comment by deverant** [comment]
Hey,

Sorry for the late reply. 

I don't currently run this on a GCE instance so I couldn't answer that. I might have a need later on to look at that but not right now. So feel free to remove mention of it for now.

I can have a look if I can reliably test this using Python3. Wouldn't mind switching to be honest.

**Comment by fdr** [comment]
On Tue, May 10, 2016 at 1:59 AM Samuel Kohonen <notifications@github.com>
wrote:

> Hey,
>
> Sorry for the late reply.
>
> I don't currently run this on a GCE instance so I couldn't answer that. I
> might have a need later on to look at that but not right now. So feel free
> to remove mention of it for now.
>
> I can have a look if I can reliably test this using Python3. Wouldn't mind
> switching to be honest.
>

Alright. I've actually done a couple of false starts on porting
WAL-E...it's mostly 2to3 compatible. I think it's tractable, though the
diff is large.

**Comment by deverant** [comment]
Hey! 

Sorry, didn't really get too far with this. Trying to 2to3 the project wasn't as simple as I had hoped. Is there a chance that we can merge this already now? And when you have a branch somewhere with most of python3 work done for the core parts I am more than happy to test and make sure the GCS parts work and provide any fixes to that part of the codebase as needed.

**Comment by fdr** [comment]
Yeah, I am going to merge this. I do have a bunch of python3 work in https://github.com/fdr/wal-e/tree/2to3wip

**Comment by fdr** [comment]
Committed in https://github.com/wal-e/wal-e/commit/c82114e4441b7b31365db223ef32dee6b8677f61 though there is a problem with one integration test I'm trying to figure out...

**Comment by deverant** [comment]
Is the problem with the GCS tests? If so I can checkout your branch tomorrow and have a look at it.

**Comment by fdr** [comment]
On Tue, Jul 12, 2016 at 4:10 PM Samuel Kohonen <notifications@github.com>
wrote:

> Is the problem with the GCS tests? If so I can checkout your branch
> tomorrow and have a look at it.
>
I actually found the bug: a parameter inversion. Steaming along, now. I'll
commit the fix shortly.

**Comment by TamalSaha** [comment]
Thanks @deverant and @fdr for adding this feature. Can we get a new release of WAL-e so that we can install this with needing to use master directly?

**Comment by fdr** [comment]
I'd like to do that, but the gcloud dependency has been giving me periodic trouble: https://github.com/GoogleCloudPlatform/gcloud-python/issues/2013, https://github.com/GoogleCloudPlatform/gcloud-python/issues/1979

I think I'm going to have to implement optional backends. Upstreams, save Azure and AWS, have packaging that is too unreliable to punish everyone for.

**Pull request closed without merging**
