### PR TITLE
Add Google Cloud Storage support

### PR DESCRIPTION
**Pull request by fdr**
Original version by Matt Wright.

Heavily modified (to use the gcloud driver) by Daniel Farina.

Errata: I am quite sure gs instance metadata is not working in this
patch.

Also, for whatever reason, I had a hard time getting blob
upload/download to work, so everything is done via signed URLs.

### CODE REVIEW

**Comment by fdr** [comment]
@mattupstate what do you think? Per the errata it could use some careful going over and testing. I do have integration tests so there's that...

**Comment by fdr** [comment]
And yeah, I'll probably break up the patch a bit, e.g. there was some refactoring to the blackbox system...but I wanted to flag your interest.

**Comment by fdr** [comment]
@RichardKnop  also relevant to your interests maybe.

**Comment by Firefishy** [comment]
Would be awesome if this could be merged ;-)

**Comment by fdr** [comment]
Does it work for anyone in the field though? I suppose I could "merge and see what happens".

**Comment by fdr** [comment]
I would like one field test at least, though, from someone invested in the feature and finding bugs.

**Comment by codefx9** [comment]
fdr, can you outline what type of test you are envisioning?

**Comment by fdr** [comment]
Using it, more or less. Making sure it works, both on backup and restore. Fixing any big surprises.

**Comment by deverant** [comment]
I've done some preliminary tests with this branch and apart from the one pull request (https://github.com/fdr/wal-e/pull/2) against your branch haven't found any problems with the code.

I will still test all the commands and look at the documention. Hope this will help to get this PR merged. :)

**Comment by fdr** [comment]
On Wed, Feb 24, 2016 at 1:03 AM Samuel Kohonen <notifications@github.com>
wrote:

> I've done some preliminary tests with this branch and apart from the one
> pull request (fdr#2 <https://github.com/fdr/wal-e/pull/2>) against your
> branch haven't found any problems with the code.
>
> I will still test all the commands and look at the documention. Hope this
> will help to get this PR merged. :)
>
That is *very* helpful :)

Most crucially, backup and restore must work.

**Comment by deverant** [comment]
Hey, continued testing this branch. 

After a painful afternoon of debugging I came across this: https://developers.google.com/api-client-library/python/guide/thread_safety

Because of this the delete operations fail since two greenlets will try to use the same socket. I guess the most sane option is the write a wrapper around some thread-safe http client to expose a `httplib2.Http` interface and inject that into the storage.Client() when it's created.

Do you want me to have a look at adding something like that or you want to do it yourself?

**Comment by fdr** [comment]
On Fri, Mar 4, 2016 at 7:55 AM Samuel Kohonen <notifications@github.com>
wrote:

> Hey, continued testing this branch.
>
> After a painful afternoon of debugging I came across this:
> https://developers.google.com/api-client-library/python/guide/thread_safety
>
> Because of this the delete operations fail since two greenlets will try to
> use the same socket. I guess the most sane option is the write a wrapper
> around some thread-safe http client to expose a httplib2.Http interface
> and inject that into the storage.Client() when it's created.
>
> Do you want me to have a look at adding something like that or you want to
> do it yourself?
>

Holy moly. Good find.

Also note that I am not using google api client, though I probably should
have tried...when I retrofitted it, I didn't find the the new new thing,
https://github.com/google/google-api-python-client.  Instead, I used
https://github.com/GoogleCloudPlatform/gcloud-python (for no reason other
than I did my best to pick it out of the conflicting documentation I read
about how to do these things at the time).

**Comment by fdr** [comment]
On Fri, Mar 4, 2016 at 7:55 AM Samuel Kohonen <notifications@github.com>
wrote:

> Do you want me to have a look at adding something like that or you want to
> do it yourself?
>
Please do feel encouraged to do what you think is necessary to bring the
patch up to bar.

**Comment by deverant** [comment]
Just to let you know that I haven't stopped.

I currently run a small database cluster in production that uses WAL-E and GCS. There are still a few quirks to fix and the whole thing needs a bit more testing. But all in all it's starting to look pretty good!

**Comment by fdr** [comment]
Cool! What did you end up doing about the whole thread safety issue?

**Comment by deverant** [comment]
Google's API allows you to pass in a new Http object as long as it has all the features of the httplib2 Http object. What I did was just encapsulate the original into a new object that links all method calls to a thread local version of Http.

I'll try to get the changes visible somewhere any day now.

**Comment by PSG-Luna** [comment]
I'm pending on this for my production setup, is the concurrency-fixed version of this available anywhere ?

**Comment by deverant** [comment]
Ok, the version I'm currently using myself that seems to do the job can be found here:
https://github.com/deverant/wal-e/tree/gcs_support

The branch is based directly on top of this pull request.

**Comment by PSG-Luna** [comment]
Been using this for several days now, can confirm everything works perfectly :)

**Comment by deverant** [comment]
@fdr, I've now been running this for a few weeks with daily successful restore tests. Should we proceed to wrap it up and get it to master?

**Comment by fdr** [comment]
That sounds good, can you submit the PR?

**Comment by fdr** [comment]
superseded by #237

**Pull request closed without merging**
