### PR TITLE
Disable query timeout for backup push.

### PR DESCRIPTION
**Pull request by sethrosenblum**
@fdr this should supercede #190 

Rebased agains v0.9, new base for PR.

### CODE REVIEW

**Comment by sethrosenblum** [comment]
Looks like travis failed on merge problems with pbr.  @fdr this good to merge?

**Comment by fdr** [comment]
Two things:

* Try rebasing, I fixed the `v0.9-oldest` tox environment and travis should be unbitrotted once more. The cause was dependency problems from `python-keystoneclient`.

* That `COMMIT` is not necessary, and generates that warning. Let's remove that (and the comment) entirely.

**Comment by sethrosenblum** [comment]
Updated.  @clofresh seems to think the commit is still necessary, so I'll do some testing.

**Comment by fdr** [comment]
He may thinking about the `SET LOCAL`. A regular `SET` is `SET SESSION` which lasts as long as the connection is alive (or settings are once again modified).

**Comment by sethrosenblum** [comment]
Yep, this appears to work: 
```
> SELECT pg_sleep(6);
ERROR:  canceling statement due to statement timeout
Time: 5000.403 ms
> SET statement_timeout = 0; SELECT pg_sleep(6);
SET
Time: 0.190 ms
 pg_sleep 
----------
 
(1 row)

Time: 6002.403 ms
```

**Comment by fdr** [comment]
Merged into v0.9

**Comment by fdr** [comment]
36e2050cf709251cd4e2002d461e16ef9a7009c3

**Pull request closed without merging**
