### PR TITLE
handle uploading string chunks while uploading to WABS

### LINKED ISSUE #277: TypeError with Python 3.4 / Azure storage
Hello, trying to perform a `backup-push` with python 3.4 and using the azure storage I get the following error:

```
The exception type is <class 'TypeError'> and its value is Unicode-objects must be encoded before hashing

wal_e/blobstore/wabs/wabs_util.py", line 89, in upload_chunk
            check_sum = base64.b64encode(md5(chunk).digest()).decode('utf-8')

```

I tried wal-e 1.0.0b1 and 1.0.0a2 and both result in the same error.

### PR DESCRIPTION
**Pull request by perfectayush**
This should handle all chunk uploads via StringIO streams to azure blob storage service. fixes #277

### CODE REVIEW

**Comment by perfectayush** [comment]
fixed for pep8

**Comment by fdr** [comment]
Awesome. It's going in.

**Comment by fdr** [comment]
By the way, have you confirmed that this fixes your problem with taking backups? If so, I'd like to release v1.0.1

**Comment by perfectayush** [comment]
Yes, I confirmed with "backup-push" command today. I was able to successfully take a full backup in a second try.

I had encountered another issue in my first try. The issue is definitely in the azure library as the message in exception had no reference in the wal-e code. This other exception happened while retrying for exception caused by operation time out while uploading to wabs. It was related to positional argument "status_code" missing. I found the reference to in  __new__ function in AzureHttpError Exception class in azure-common. I was not able to reproduce it my second try.

**Comment by fdr** [comment]
Do you think there's a fix we should put into that? I'm trying to avoid cutting too many point releases is all.

**Comment by perfectayush** [comment]
No, I don't think we need to fix it, its not an issue with wal-e. It seemed to me that azure api didn't give a proper response that's why it failed. I was getting a lot of operation timed out exception in my first try, that didn't happen the second time. I was not able to reproduce it, so couldn't dig deep.

**Comment by fdr** [comment]
Did it retry successfully, or did it crash WAL-E unnecessarily?

**Comment by perfectayush** [comment]
It crashed wal-e. I lost the exception log else I would have posted here. It said that during handling exception another exception occurred. We will be running it in production soon and logging it. I will post an issue here if we encounter it again. 

Currently, we are on wal-e 0.7 and just realized that our backups were failing in azure due to various exceptions. I noticed that there are lot of azure related fixes in 1.0, so was testing it when I encountered issue above. We have infra both in azure and s3. So before switching versions, I will ensure that everything thing is working as expected.

**Comment by fdr** [comment]
Okay, I think I will release a WAL-E point release tomorrow if you don't
find anything new before then. Let me know if you want to put anything else
in 1.0.1.

Thanks for looking into this and fixing it!

**Pull request merged**
