### PR TITLE
Update google-storage and handle retries

### PR DESCRIPTION
**Pull request by kshelton**
* Clean up threaded client to be more tolerant of library changes
* Update tox file
* (Bug) Pipelining closing wrong descriptor
* Make download use blob download instead of urllib directly

### CODE REVIEW

**Comment by kshelton** [comment]
Failed check seems unrelated to commit

**Comment by deverant** [comment]
Hey @kshelton , thanks for the PR!

Really looking forward to getting the updated google library into production. :)

I'll try to find some time to test this myself but have you tried running these changes in production? The changes themselves look clear enough, I'd just like to verify that the google library still works as expected.

**Comment by kshelton** [comment]
Yes, I'm currently using it in production.  I had cut over from using the SWIFT capability layer to the GCS code in June and it turns out at that point my full backups stopped working.

I was attempting to test my backups and realized I had to replay 2.5 months of backups.  Even replaying the WAL kept failing out, but once I cut these changes over my full backups started working again.

**Comment by deverant** [comment]
Hey, just a heads up that I haven't forgotten about this. I'm building a package of wal-e with these changes myself right now to test it properly.

I noticed that the tests are now all failing because your changes to gs_worker made `datetime` an unused import. Can you fix that in the PR when you have the chance, please?

**Comment by listingmirror** [comment]
Wal-e has been very flaky for me on google as of late. I get "hung" pushing a segment and it never leaves, requiring me to kill the wal-e process. So far this pull request is working 100x better. Assuming it keeps up this seems like a good improvement.

**Comment by kshelton** [comment]
@deverant Sorry the github email was buried in my clutter folder.  I removed the import.

**Comment by deverant** [comment]
Ok, been testing this out and haven't seen any regressions. The download speeds _feel_ a bit slower, but nothing that I can put into numbers.

@kshelton , do you mind if I rebase this into a single clean commit and merge ahead?

@fdr , I think this might be the solution needed for #307. Should we consider releasing 1.1 once this is merged?

**Comment by kshelton** [comment]
@deverant  I dug my way through the SDK code again and I think my initial assumption that a non chunk forced download would try to buffer all in RAM first was wrong. I have since removed the chunk size specification and that should cause you to see increased performance.  I also rebased.

**Comment by kshelton** [comment]
@deverant Did you get a chance to verify with the change?

**Comment by deverant** [comment]
Hey @kshelton, all looks good. I'll pretty up the commit message a bit and merge the change. Thanks for doing the heavy lifting! :)

**Comment by deverant** [comment]
Merged in c77bf2b

**Pull request closed without merging**
