### PR TITLE
Fix incompatiblity with some S3 implementations

### PR DESCRIPTION
**Pull request by sebastianneubauer**
The boto delete_keys function is not compatible with all S3 implementations (e.g. google or fakes3). This fallback should fix it...

The issues where this problem is reported is #192

### CODE REVIEW

**Comment by fdr** [comment]
Generic S3ResponseError is too generic. Is there any way to be more specific?

**Comment by sebastianneubauer** [comment]
I can check, but it might be, that there are no more details, as the 3rd party server api like fakes3 doesn't "know" this request, and boto just expects this bulk delete to be implemented. So the client and server apis just doesn't fit together (which is of course bad and should be fixed...)

**Comment by sebastianneubauer** [comment]
Ok, one can check the status code in addition, would that be sufficient? 
`S3ResponseError: S3ResponseError: 400 Bad Request`

**Comment by fdr** [comment]
I think that is probably sufficient. I was expecting a 400-class code.

**Comment by fdr** [comment]
Also, though regrettably it can be challenging, see if you can look for a way to inject the fault for a test.

**Comment by sebastianneubauer** [comment]
Yes, I will write a test, first wanted to get feedback if it is worth the effort ;-)

**Comment by fdr** [comment]
Poke. Do you want to fix this matter? If so, re-open the PR at your leisure.

**Pull request closed without merging**
