### PR TITLE
AWS S3 Available regions and names update at 11 May 2018. 

### PR DESCRIPTION
**Pull request by Antiarchitect**
Please see https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region.
I'm just lacking of us-east-2 but performed update accordingly current state of things.

### CODE REVIEW

**Comment by profilernz** [comment]
Sure, this is an important and needed update.
Just pointing out after your posted on my other issue...

**Comment by Antiarchitect** [comment]
What's up with the project? Seems all stalled.

**Comment by deverant** [comment]
Hey, makes sense to update this mapping. I haven't ever used wal-e with S3 myself though, so since I am not familiar with the codebase I'm hoping @fdr can sign off on this one. Not sure if this is the only thing that needs to change.

**Comment by Antiarchitect** [comment]
It actually solves my problem with us-east-2. After this: https://github.com/zalando/spilo/pull/242 my backups have landed to S3 properly.

**Comment by deverant** [comment]
Fair enough. I can't really see any problems with this change so will go ahead and merge.

**Pull request merged**
