### PR TITLE
Raise exception in S3 deleter if multiple delete partially fails

### LINKED ISSUE #271: Make deletion success or failure more apparent with S3
When there is no deletion right, command appears succcessful but actually did nothing and no error message.

### PR DESCRIPTION
**Pull request by secwall**
Closes #271.

### CODE REVIEW

**Comment by fdr** [comment]
There seems to be a non-termination issue in here.

**Comment by secwall** [comment]
May be retry should be finite?

**Comment by fdr** [comment]
If retries are the culprit, wal-e shouldn't retry a `UserException`. If there's code that has gone through the trouble to wrap/convert an exception to a `UserException`, wal-e should terminate. If you don't think WAL-E should terminate immediately in this case, merely logging is what ought to be done.

**Comment by secwall** [comment]
Hm, tests failed because result of `bucket.delete_keys` call was `None` in some cases.
I've tried to run deletion with read-only user on AWS S3 and it seems that retries are still infinite. Retrying multiple delete makes sense because sometimes AWS fails to remove all keys, such cases are quite rare though. May be there should be `retry_with_count` and side-effect function to apply some reasonable limit instead of just `retry`. Am I missing something obvious?

**Comment by secwall** [comment]
Hello. I've limited number of retries in S3 deleter. Now it stops after 3 failed attempts. @fdr could you kindly take a look?

**Comment by fdr** [comment]
Okay. I've thought about this (clearly at some length, now) and I think it makes sense to use `stdout`  of wal-e to communicate deletion errors. Maybe like `backup-list`. The `csv` module could be useful to this purpose.

That's because I think making a user fix ACL issues up-front to continue deletion (because of exceptions) is somewhat cruel, so generating report of the errors that can be handled by machine, if necessary, might make more sense.

**Comment by secwall** [comment]
Good idea. What fields should we display to user in case of failure?
Is combination of key and error sufficient?

**Comment by fdr** [comment]
I think so. One thing may be to not print multi-line errors if possible, because it'll mess up `grep` and other line-oriented programs.

**Comment by secwall** [comment]
Hello. Now error message will look like this:
```
[07:50:46 root@trusty64:~] # envdir /etc/wal-e.d/env/ wal-e delete --confirm everything 2>/dev/null
key     error_code      error_message
backup-test/wal_005/000000010000000000000007.lzo        AccessDenied    Access Denied
backup-test/wal_005/000000010000000000000008.lzo        AccessDenied    Access Denied
backup-test/wal_005/000000010000000000000001.lzo        AccessDenied    Access Denied
backup-test/wal_005/000000010000000000000009.lzo        AccessDenied    Access Denied
```
Is this ok?

**Comment by fdr** [comment]
That does look okay.

**Pull request merged**
