### PR TITLE
File blobstore

### PR DESCRIPTION
**Pull request by colmaengus**
Reissue of #202 based on v0.9 instead of master.

### CODE REVIEW

**Comment by fdr** [comment]
Do any @wal-e/committers have time to process this patch? It should go into the v0.9 tree (which fixes some test bitrot). I am currently handling Google Storage on and off myself.

**Comment by tbeadle** [comment]
I just ran tox with this diff applied to the current master branch and there were no failed tests.  Could we please try to apply this again.  I'd love to see local file support added to wal-e.

**Comment by colmaengus** [comment]
@fdr : any chance of getting this into the upcoming 1.0.0 release ?

**Comment by fdr** [comment]
No. We're at the very end of the release cycle. If someone did fix this up and forward-port it to Python3 (as v1.0 is) I would release 1.1.0 sooner rather than later.

**Comment by colmaengus** [comment]
Understood. I'll see how I'm fixed for time to do this.

**Comment by fdr** [comment]
I'm applying the newly introduced `needs-work` label to this. That is, there is no problem with the feature in principal, but there's a lack of interest, testing, or changes to complete it. I also apply this label so I can find such closed pull requests easily for future study.

**Comment by charles-dyfis-net** [comment]
I'm actually in a position to put some time into this during business hours. Should I open a separate PR when I have something working? Any pointers in terms of additional effort that needs to happen, beyond getting the tests to pass?

**Comment by fdr** [comment]
On Tue, Apr 11, 2017 at 1:51 PM Charles Duffy <notifications@github.com>
wrote:

> I'm actually in a position to put some time into this during business
> hours. Should I open a separate PR when I have something working? Any
> pointers in terms of additional effort that needs to happen, beyond getting
> the tests to pass?
>
Sure, a separate PR is preferred.

Tests, particularly adding a blackbox test, would help a lot. Also,
actually trying to backup/restore. That's about it.

**Comment by charles-dyfis-net** [comment]
Work-in-progress presently exists as https://github.com/wal-e/wal-e/compare/wal-e:e9b7f31...charles-dyfis-net:0458cd5; will submit as a PR after integration testing.

**Pull request closed without merging**
